### ISSUE TITLE
xcode-select version 2398. too outdated

### ISSUE THREAD

**Issue by maxwowpow** [nailuoGG/homebrew-recoll#4]
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 15.0.

xcode-select version 2398.

**Comment by nailuoGG** [comment]
Hello,

Due to the complexity of configuring the compilation environment for QT software on macOS, this repository will initially provide only the installation method through dmg files until there's familiarity and proficiency with QT development.

The dmg files are directly compiled and built by the author of the Recoll software. For your reference, here is the source link: https://www.lesbonscomptes.com/recoll/pages/recoll-macos.html

We appreciate your understanding and patience. Should you have any further questions or need assistance, feel free to reach out.

Best regards.
